baseURL = "http://example.com/"
languageCode = "en-us"
title = "Third Day Horticulture"
theme = "minimal-master"

[menu]

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 2

[[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 3

[params]
    author = "Dan Burgett"
    tagline = "Founded in 2016, our company is dedicated to helping businesses and residents of Tyler, Texas create beautiful floral pots and planters."
    description = "We can help with simple consultation, installation and maintenance of any landscape.  We are not afraid to get our hands dirty!"
    githubUsername = ""
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!

# Portfolio section
[params.portfolio]
  enable = true
  # All projects defined in their own files. You can find example projects
  # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
  # at the root of this Hugo site.
  # For more informtion take a look at the README.
  title = "Previous Customers"

  [params.portfolio.modal]
    client = "Client"
    date = "Date"
    category = "Category"
    buttonText = "Close project"
