baseURL = "http://example.com/"
languageCode = "en-us"
title = "Third Day Horticulture"
theme = "minimal-master"

[params]
    author = "Dan Burgett"
    tagline = "We are dedicated to helping businesses and residents of Tyler create beautiful floral pots and planters."
    description = "Our founder Alison Burgett used to work at the United States Botanic Garden in Washington D.C. She has a Masters Degree in Plant Science and a Bachelors in Horticulture."
    githubUsername = ""
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 2

[[menu.main]]
    name = "Projects"
    url  = "/projects/"
    weight = 3

#contact setion
[params.contact]
    buttonText = "Send message"
# 'warning' defines error messages for invalid inputs
[params.contact.form.name]
  text = "Your Name *"
  warning = "Please enter your name."

[params.contact.form.email]
  text = "Your Email *"
  warning = "Please enter your email address."

[params.contact.form.phone]
  text = "Your Phone *"
  warning = "Please enter your phone number."

[params.contact.form.message]
  text = "Your Message *"
  warning = "Please enter a message."

# Portfolio section
[params.portfolio]
  enable = true
  # All projects defined in their own files. You can find example projects
  # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
  # at the root of this Hugo site.
  # For more informtion take a look at the README.
  title = "Projects"

  [params.portfolio.modal]
    client = "Client"
    date = "Date"
    category = "Category"
    buttonText = "Close project"
